// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgxgxcdmojvghfhvfvxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNneGd4Y2Rtb2p2Z2hmaHZmdnhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MDU5NTUsImV4cCI6MjA2NjQ4MTk1NX0.LWyO2h2n2-YjFKM-LedGbVAJzDHXYy4peC5dEpRg8lM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});